### ISSUE TITLE
코잇 클라이언트 코드 리팩토링

### ISSUE THREAD

**Issue by KimKwon** [CO-EAT/CO-EAT-CLIENT#8]
# ⚒️  클라이언트 코드 리팩토링

## :hammer: What for

낮은 확장성, 낮은 재사용성, 낮은 가독성... 
솝커톤이 끝나고도 미련이 남아 완성도 높은 코드로 만들어보고자 리팩토링을 결심하게 되었음.

## 🔥   Focus on

1.  역할이 명확히 구분된 컴포넌트 작성
2. css-in-js 준수, classname 사용 최소화
3. 시멘틱 태그 사용 (div 남발 X)
4. 의미 있는 변수 네이밍
5. 공통 스타일 요소 분리 및 Mixin 적용

## ✅   To do
- [x] : 뷰 완성
- [x] : API 연결
- [x] : 이미지 애셋 처리 방식 고민 (스토리지 고려)
- [x] : 로컬스토리지 사용 코드 제거
- [x] : Constants 로 분리할 코드 식별/추출
- [x] : Lint Rule 추가

**Comment by younyikim** [comment]
가보자고..

**Comment by Gyuminn** [comment]
화이팅 해보자고
